---
var_1: &default_docker_image node:11
version: 2.1

commands:
  chaperone2build:
    description: "Build command"
    steps:
      - checkout
      - run:
          name: Build
          command: yarn install

  chaperone2deploy:
    description: "Command to deploy to different use cases"
    parameters:
      to:
        type: string
        default: ""
    steps:
      - run:
          name: Deploy << parameters.to >>
          command: yarn run deploy<< parameters.to >>

jobs:
  build-test:
    docker:
      - image: *default_docker_image
    steps:
      - chaperone2build
      - run:
          name: Test
          command: |
            yarn test

  deploy:
    docker:
      - image: *default_docker_image
    steps:
      - chaperone2build
      - chaperone2deploy:
          to: ""
      - chaperone2deploy:
          to: "-static"

  # beta-deploy:
  #   docker:
  #     - image: *default_docker_image
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build
  #         command: |
  #           yarn install
  #     - chaperone2deploy:
  #         to: "-beta"

  cloudfront-invalidate:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - run:
          name: Invalidate
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /embed.js /embed.js.map

workflows:
  version: 2
  chaperone-workflow:
    jobs:
      - build-test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build-test
      - cloudfront-invalidate:
          filters:
            branches:
              only: master
          requires:
            - build-test
            - deploy


