---
version: 2
jobs:
  build-test:
    docker:
      - image: node:11
    steps:
      - checkout
      - run:
          name: Build
          command: |
            yarn install
      - run:
          name: Test
          command: |
            yarn test

  deploy:
    docker:
      - image: node:11
    steps:
      - checkout
      - run:
          name: Build
          command: |
            yarn install
      - run:
          name: Deploy to s3
          command: |
            yarn run deploy
      - run:
          name: Deploy static copy to s3
          command: |
            yarn run deploy-static

  cloudfront-invalidate:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - run:
          name: Invalidate
          command: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /embed.js /embed.js.map

workflows:
  version: 2
  chaperone-workflow:
    jobs:
      - build-test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build-test
      - cloudfront-invalidate:
          filters:
            branches:
              only: master
          requires:
            - build-test
            - deploy


